### ISSUE TITLE
Connect: report non-compatible pairs as failures

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit_task_constructor#201] opened 2020-08-27 14:35 UTC

**Comment by v4hn** [comment] 2021-03-22 14:06
This should be optional, because there will usually be *many* failing pairs.
We could try to filter the failure reasons and only report each reason (except for numeric changes) once.

This has to be implemented around [here](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/src/stage.cpp#L714)

**Comment by v4hn** [comment] 2021-03-22 14:57
duplicate of #49

**Closed by v4hn** 2021-03-22 14:57 UTC
Labels: enhancement
