### ISSUE TITLE
demo->cartesian

### ISSUE THREAD

**Issue by Reaper151** [ros-planning/moveit_task_constructor#158] opened 2020-04-12 12:46 UTC
I tried to integrate moveit_task_controller to our robot and when I ran cartesian demo it provide solution on +x task because there are waypoints in "MoveIt Planning Tasks-Slider" and it can animate but the states fell under "fail solution attempts".

Edit: I tried joint_interpolation to move arm into group state as define in SRDF it worked but still have no idea why cartesian interpolation and pickplace demo not working.

**Comment by iamrajee** [comment] 2020-04-12 18:36
> have no idea why cartesian interpolation and pickplace demo not working.

Can you provide more information with error message?

**Comment by Reaper151** [comment] 2020-04-13 02:06
> > have no idea why cartesian interpolation and pickplace demo not working.
> 
> Can you provide more information with error msg?

That's the problem I don't see any error logs in console.

**Comment by iamrajee** [comment] 2020-04-13 05:12
> That's the problem I don't see any error logs in the console.

Please provide more information like ROS distro, your system and whether your moveIt is binary or source built?
Also, provide the steps to reproduce this issue and screenshot of rviz MTC task panel.

**Comment by Reaper151** [comment] 2020-04-13 09:39
Problem solved. 
It looks like to be a physical limitation of my robot arm that can't do the task but I frustrated at first because it can be animate and arm is following the motion. 
PS. ROS Melodic and moveIt was built by source

Now I resume to get pickplace works but I stuck at "grasp_pose_IK" for a while.
![image](https://user-images.githubusercontent.com/43701351/79110712-0040fb80-7db6-11ea-981d-441cc4b3725a.png)

**Comment by Reaper151** [comment] 2020-04-13 11:40
@iamrajee if I want to discuss about stuck at "grasp_pose_IK" in demo->pickplace should I open new issue?

**Comment by iamrajee** [comment] 2020-04-13 16:31
@Reaper151 Common cause for IK failure is when the object is unreachable, but assuming this is not the case with you as you've already experimented with various object_pose. 
Although we have forbidden the collision between gripper and object before picking in the demo, it may so happen that some other part of the robot could be in collision with it while picking thus resulting in IK failure. You can increase the distance between gripper and object while picking by changing `grasp_frame_transform`. e.g for panda arm you can do something like
```
grasp_frame_transform: [0, 0, 0.2, 1.571, 0.785, 1.571] #here 0.2 is that distance
```
Of course for your robot this could be different. If the problem still persists then surely go ahead and open a new issue.

**Comment by v4hn** [comment] 2020-04-14 19:14
From the picture it still looks like the requested pose might not be reachable.
Can you move your arm by hand (or in simulation by slider) to the pose you want to reach?

Are the failing solutions associated with a comment (extend the right listing of individual solutions to see the comments section)?

**Comment by Reaper151** [comment] 2020-04-14 19:56
All it need to do is just move back a little bit less than 0.2m in cartesian demo that i succeed.
![image](https://user-images.githubusercontent.com/43701351/79268241-653f4300-7ed5-11ea-9581-0decc1c5bf9a.png)

**Comment by v4hn** [comment] 2020-04-15 09:13
I'm not sure how to support you at all right now.

To simplify the task, you can reduce it to a simple 
`CurrentState` - `Connect` - `grasp pose IK (generate grasp pose)` structure.

But your problem remains that IK fails for the requested pose I guess.
This is either because the pose is indeed not reachable, your IK solvers are incomplete, or because of an unexpected collision you did not consider (might be an accidentally allowed collision between unrelated links of the robot).

**Comment by Reaper151** [comment] 2020-04-15 12:58
@v4hn  For what it might worth, I have succeed in mitigrate MoveIt Grasp Demo.
I will recheck allowed collision again is there any turorial that will check and visualize the collision before move?

**Comment by v4hn** [comment] 2020-04-15 13:40
On Wed, Apr 15, 2020 at 05:58:55AM -0700, Reaper151 wrote:
> @v4hn  For what it might worth, I have succeed in mitigrate MoveIt Grasp Demo.
> I will recheck allowed collision again is there any turorial that will check and visualize the collision before move?

No there isn't, but you can try to set the `ignore_collisions` property (setIgnoreCollisions) to false to ensure that's not the problem.

**Comment by Reaper151** [comment] 2020-04-16 03:57
Ah. It's collision problem as I set the `ignore_collisions` property (setIgnoreCollisions) to true, then pipeline is complete.

Does computeIK refer to 'disble_collisions' tags in SRDF because I found one pair of link that collided but already has 'disable_collisions' by 'adjacent' reason in SRDF but problem remained?

**Comment by rhaschke** [comment] 2020-04-16 06:51
The allowed collision matrix (ACM) defined in the SRDF should be considered by ComputeIK. I guess there is another collision as well. If you increase the width of the solution view, you will see a comment explaining the reason of failure:
![image](https://user-images.githubusercontent.com/5376030/79423679-5208a200-7fbf-11ea-93d6-0c4f83ba2738.png)

Also, you may notice that the visualization of the end effector changes from visual to collision geometries depending on the error type (i.e. IK failure vs. collision).

**Comment by Reaper151** [comment] 2020-04-16 07:39
Thanks problem solved it's other collision cause by my workspace. Appreciate for all of your help.
This is conclusion.

> The allowed collision matrix (ACM) defined in the SRDF should be considered by ComputeIK. I guess there is another collision as well. If you increase the width of the solution view, you will see a comment explaining the reason of failure:
> ![image](https://user-images.githubusercontent.com/5376030/79423679-5208a200-7fbf-11ea-93d6-0c4f83ba2738.png)
> 
> Also, you may notice that the visualization of the end effector changes from visual to collision geometries depending on the error type (i.e. IK failure vs. collision).

Anyway do you have any plan for wrapper of pickplace in python?

**Comment by rhaschke** [comment] 2020-04-16 08:14
I do have a lot of plans for python, but no time to implement them...
If this issue is solved, please close it, @Reaper151.

**Comment by v4hn** [comment] 2020-04-16 08:14
>  This is conclusion.

Closing.

> Anyway do you have any plan for wrapper of pickplace in python.

Robert has work in progress for usable python bindings that would allow for it, but time is short.

**Closed by v4hn** 2020-04-16 08:14 UTC

**Comment by Reaper151** [comment] 2020-04-16 08:16
I'm looking forward to see it!!!
Cheers
